name: update-gh-pages
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@2
        uses: actions/setup-node@2
        with:
          node-version: '16'
      
      - name: build
        run: npm ci
        run: npm run build

      - name: depoly
        run: git add .
        run: git commit -m 'github-actions-commit'
        run: git remote remove origin
        run: git remote add origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git
        run: git push --set-upstream origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_REPO: vue-little-minesweeper
